configurations/blueprints.py
from chats import from_chats
from reg import from_reg
from main import from_main

blueprints = (

    from_chats,
    from_main,
    from_reg,

)

main/__init__.py
from flask import Blueprint


from_main = Blueprint('main', __name__, template_folder='templates',
                      static_folder='static', static_url_path='/%s' % __name__)

from . import views

main/views.py
from flask import render_template, abort, request, session, redirect, url_for
from flask_socketio import emit
from configurations.settings import ConfigClass
from chats import socket_io
from main.tools import users_context, slash
from os import path, makedirs
from werkzeug.utils import secure_filename
from . import from_main


extra = from_main


@extra.route('/')
def index_page():
    context = {}
    return render_template('base.html', context=context)


@extra.route(r'/config', methods=['POST'])
def user_conf():
    if request.method == 'POST':
        from models.models import User, db

        q = User.query.filter_by(id=session.get('user_id')).first()
        if q is None:
            abort(404)
        User.re_write_config(q)
        db.session.commit()

    return redirect(url_for('main.index_page'))


@extra.route(r'/upload_image', methods=['POST'])
def upload_img():
    u = str(session.get('user_id'))
    s = slash()
    f = request.files.get('image')
    if request.method == 'POST' and f:
        filename = secure_filename(f.filename)
        if filename.split('.')[-1] not in ['jpg', 'png', 'jpeg']:
            return render_template('reg/flash_message.html',
                                   context={'msg': 'Bad format, need: jpg, jpeg, png'})

        user_directory = ConfigClass.ABSOLUTE_IMAGES_FOLDER + s + u
        if not path.exists(user_directory):
            makedirs(user_directory)

        path_to_file = user_directory + s + u + '.jpg'
        f.save(path_to_file)
    return redirect(url_for('main.index_page'))


@socket_io.on('page', namespace='/main')
def page_context(data=None):
    from models.models import User

    current_id = session.get('user_id')
    query = User.query.filter_by(id=current_id).all()
    context = users_context(query)

    return emit('userData', context)


@socket_io.on('friends', namespace='/main')
def people_context(data=None):
    from models.models import User

    current_id = session.get('user_id')
    query = User.query.all()
    context = users_context(query, current_id)

    return emit('people', context)

main/templates/main/chatWindow.html
<div class="frame">
    <div class="showMessages" id="scroll_div">
        <div class="wall"></div>
    </div>
    <div class="typeMessage">
        <div class="myPhoto friendPhoto">
            <img id="myPhoto">
        </div>
        <textarea id='newMessage'></textarea>
        <button id="buttonMessage" class="sendMessage">Send</button>
        <div class="friendPhoto">
            <img id="friendPhoto">
        </div>
    </div>
</div>

main/templates/main/configuration.html
<form id='myPageConfig' method="post" action="{{ url_for('main.user_conf') }}">
    <div class="labels">
        <label for="last_name">Last Name: </label>
        <label for="first_name">First Name: </label>
        <label for="status">Status: </label>
        <label for="city">City: </label>
        <label for="phone">Phone: </label>
        <label for="birthday">Birthday: </label>
    </div>
    <div class="inputs">
        <input type="text" id="last_name" name="last_name">
        <input type="text" id="first_name" name="first_name">
        <input type="text" id="status" name="status">
        <input type="text" id="city" name="city">
        <input id="phone" name="phone" type="tel">
        <input id="birthday" name="birthday" type='date' max="2015-12-31">
    </div>
    <button class="sendMessage">Apply</button>
</form>

main/templates/main/index.html
<!-- left-side menu -->
<div class="left-side">
    <h1 class="mainLogo" onclick="myPage()"><span>Cup</span>Cake</h1>
    <h1 class="mainLogo mediaLogo" onclick="myPage()"><span>C </span>C</h1>
    <ul>
        <li id="myPage" class="active">
            <a onclick="myPage()"><i class="fa fa-desktop"></i><span>My page</span></a>
        </li>
        <li id="myFriends">
            <a onclick="myFriends()"><i class="fa fa-users"></i><span>People</span></a>
        </li>
        <li id="myConfiguration">
            <a onclick="myConfiguration()"><i class="fa fa-pencil-square-o"></i><span>Configuration</span></a>
        </li>
        <li id="logout">
            <a href="{{ url_for('reg.logout') }}"><i class="fa fa-sign-out"></i><span>Logout</span></a>
        </li>
    </ul>
</div>
<!-- Main container for the inf -->
<div id="wrapper">
    <div id="Page" hidden>{% include 'main/myPage.html' %}</div>
    <div id="Friends" hidden>{% include 'main/myFriends.html' %}</div>
    <div id="ChatWindow" hidden>{% include 'main/chatWindow.html' %}</div>
    <div id="Configuration" hidden>{% include 'main/configuration.html' %}</div>
</div>
<!-- Additional containers -->
<div id="Load">
    <div class="leftEye"></div>
    <div class="rightEye"></div>
    <div class="mouth"></div>
</div>
<div id="modalWindow" onclick="closeModal()">
    <div>
        <div id="imgContainer"></div>
        <div class="close" onclick="closeModal()">
            <i class="fa fa-times"></i>
        </div>
    </div>
</div>
<div class="messageNotification">
    <div class="left-block">
        <div class="friendPhoto">
            <img class="notifPhoto" src="">
        </div>
        <span class="time"></span>
    </div>
    <div class="right-block">
        <span class="name"></span><br>
        <span class="thisMessage"></span>
        <div class="close">
            <i class="fa fa-times"></i>
        </div>
    </div>

</div>

main/templates/main/myFriends.html
<article class="friends">
    <div class="myfriends original">
        <div class="friendPhoto">
            <img class='userImg' src="">
        </div>
        <div class="friendInf">
            <span class="friendName"></span>
            <div class="state"></div>
            <br>
            <span class="user-status"></span>
            <br>
            <ul>
                <!-- city -->
                <li>
                    <i class="fa fa-home"></i> <span>City:</span> <span class="city inf"></span>
                </li>
                <!-- mail -->
                <li>
                    <i class="fa fa-envelope-o"></i> <span>E-mail:</span>
        <span class="inf">
            <a class="email"></a>
          </span>
                </li>
                <!-- tel -->
                <li>
                    <i class="fa fa-phone"></i> <span>Phone:</span>
        <span class="inf">
              <a class='phone'></a>
          </span>
                </li>
                <!-- birth -->
                <li>
                    <i class="fa fa-birthday-cake"></i> <span>Birthday:</span> <span class="inf birthday"></span>
                </li>

            </ul>
            <br>
        </div>
        <button class="sendMessage">Send message</button>
    </div>
</article>

main/templates/main/myPage.html
<article>
    <!-- photo -->
    <div class="photoInf">
        <div class="mainPhoto">
            <img class='userImg' src="">
        </div>
        <div class="changePhoto">
            <i class="fa fa-file"></i> Change a photo!
            <form action="{{ url_for('main.upload_img') }}" method="post" enctype="multipart/form-data">
                <input type="file" name="image" class='changeImg'
                       onclick="document.getElementsByClassName('changeButton')[0].style.display = 'block';">
                <button class="changePhoto changeButton">OK</button>
            </form>
        </div>
    </div>
    <!-- user inf. -->
    <div class="mainInf">
        <h1 id="name"></h1>
        <div class="state"></div>
        <br>
        <span class='user-status'></span>
        <ul>
            <!-- city -->
            <li>
                <i class="fa fa-home"></i> <span>City:</span> <span id='city' class="inf"></span>
            </li>
            <!-- mail -->
            <li>
                <i class="fa fa-envelope-o"></i> <span>E-mail:</span>
        <span class="inf">
            <a id="mail"></a>
          </span>
            </li>
            <!-- tel -->
            <li>
                <i class="fa fa-phone"></i> <span>Phone:</span>
        <span class="inf">
              <a id='tel'></a>
          </span>
            </li>
            <!-- birth -->
            <li>
                <i class="fa fa-birthday-cake"></i> <span>Birthday:</span> <span id='birthday' class="inf"></span>
            </li>
            <!-- work -->

        </ul>

    </div>
</article>

<!-- write a comment -->

<!--<section>
  <div class="comments">
    <div>
      <span>Make a comment</span>
      <span>Amount of comments: <span id='amount'>3</span></span>
    </div>
    <form id='commentForm'>
      <textarea id="comment" oninput="changeTextArea(this.value)" onfocus="showPhoto()" onblur="checkArea(this.value)"></textarea>
      <div>
        <button onclick="addComment();return false;">Comment</button>
        <div class="Limage">
          <i class="fa fa-camera"></i>
          <input type="file" id='Limage' onchange="loadImg(this.value)">
        </div>
      </div>
    </form>
  </div>

  <div class="showComment">
    <div class='commentPhoto' id='mainPhComm'>
{#      <img src="img/o12S9j9oevs.png" class="userImg">#}
    </div>
    <span id='commentChg'></span>
    &lt;!&ndash; <img id='commentImg' src="" class='addImg'> &ndash;&gt;
  </div>
</section>-->

<!-- user's comments -->