reg/__init__.py
from flask import Blueprint


from_reg = Blueprint('reg', __name__, template_folder='templates',
                     static_folder='static', static_url_path='/%s' % __name__)


from . import views

reg/views.py
from flask import request, redirect, render_template, url_for, session
from flask_login import login_user, logout_user
from chats import socket_io
from flask_socketio import emit
from sqlalchemy.exc import IntegrityError
from . import from_reg

extra = from_reg


@extra.route('/register', methods=['GET', 'POST'])
def register():
    from models.models import User, ActivatedUsers
    from run_app import db

    if request.method == 'GET':
        return render_template('reg/register.html', context={})

    context = {
        'last_name': request.form.get('last-name'),
        'first_name': request.form.get('first-name'),
        'email': request.form.get('email'),
        'msg': 'Validation error',
    }

    if request.method == 'POST':
        date = User.valid_date(context)
        if date:
            user = User(first_name=date.get('first_name'), last_name=date.get('last_name'),
                        email=date.get('email'), register=True)
            activate = ActivatedUsers(user)

            for x in [user, activate]:
                db.session.add(x)
            try:
                db.session.commit()
            except IntegrityError:
                context['msg'] = 'This email has already registered'
                return render_template('reg/register.html', context=context)

            activate.send_email()

            return render_template('reg/flash_message.html', context={'msg': 'Activate your e-mail'})
        else:

            return render_template('reg/register.html', context=context)

    context['msg'] = 'Problem with registration'

    return render_template('reg/register.html', context=context)


@extra.route('/login', methods=['GET', 'POST'])
def login():
    from models.models import User, db, datetime

    context = {
        'password': request.form.get('password'),
        'email': request.form.get('email'),
        'msg': 'Sorry, but your login or password is incorrect',
    }

    if request.method == 'POST':

        query = User.query.filter_by(email=context.get('email').lower(),
                                     password=User.hash_password(context.get('password'))).first()

        if query:
            user = User(query=query)

            query.online = True
            query.active = datetime.now()
            db.session.commit()

            login_user(user, remember=True)
        else:
            return render_template('base.html', context=context)
    return redirect(url_for('main.index_page'))


@extra.route('/logout')
def logout():
    from models.models import User, db, datetime

    query = User.query.filter_by(id=session.get('user_id')).first()

    if query is not None:
        query.online = False
        query.active = datetime.now()
        db.session.commit()
        logout_user()

    return redirect(url_for('main.index_page'))


@extra.route(r'/user/activate/<s>', methods=['POST', 'GET'])
def activate_user(s):
    from models.models import User, ActivatedUsers, db

    context = {
        'msg': 'Write yours password',
        'action': "/user/activate/%s" % (s,),
    }

    query = ActivatedUsers.query.filter_by(activated_str=s).first()

    if request.method == 'GET' and query is not None:
        return render_template('reg/handling_pass.html', context=context)

    if request.method == 'POST':

        f = {
            'pass1': request.form.get('pass1'),
            'pass2': request.form.get('pass2'),
        }

        if query is not None:
            if query.activated:
                context['msg'] = 'This code has already registered'
            query.activated = True

            if User.clean_passwords(f['pass1'], f['pass2']):
                query.users.password = User.hash_password(f['pass1'])
            else:
                context['msg'] = 'Bad password'
                return render_template('reg/handling_pass.html', context=context)

            user = query.users

            login_user(user, remember=True)

            db.session.commit()

            context['msg'] = 'Your account successfully create'

            return render_template('reg/flash_message.html', context=context)

        context['msg'] = 'Wrong code'

    context['msg'] = 'Problem with activation'

    return render_template('reg/flash_message.html', context=context)


@extra.route(r'/forgot_password', methods=['POST', 'GET'])
def forgot_password():
    from models.models import User, ActivatedUsers
    context = {
        'msg': 'Please write your e-mail'
    }

    if request.method == 'POST':
        email = request.form.get('email').lower()
        q = User.query.filter_by(email=email).first()
        if User.clean_email(email) and q is not None:
            ActivatedUsers.send_email_for_password(email)
            context['msg'] = 'Check your email address and confirm the link'

            return render_template('reg/flash_message.html', context=context)

        context['msg'] = 'Wrong e-mail'

    return render_template('reg/email.html', context=context)


@extra.route(r'/user/new_password/<s>', methods=['POST', 'GET'])
def new_password(s):
    context = {
        'msg': 'Wrong code for create new password',
        'action': "/user/new_password/%s" % (s,),
    }

    if s == session.get('act_str_for_password'):
        context['msg'] = 'Please write your new password'

        if request.method == 'POST':
            from models.models import User, db

            pass1 = request.form.get('pass1')
            pass2 = request.form.get('pass2')

            if User.clean_passwords(pass1, pass2):
                query = User.query.filter_by(email=session.get('email')).first()
                query.password = User.hash_password(pass1)

                db.session.add(query)
                db.session.commit()

                del session['email']
                del session['act_str_for_password']

                context['msg'] = 'Successfully changed password'

                return render_template('reg/flash_message.html', context=context)

        return render_template('reg/handling_pass.html', context=context)

    return render_template('reg/flash_message.html', context=context)


@socket_io.on('validationEmail', namespace='/reg')
def check_unique_email(data):
    from models.models import User

    email = data.get('email')
    if email:
        q = User.query.filter_by(email=email).first()

        if q is None:
            flag = True
        else:
            flag = False

        return emit('flag', {'extra': flag})
    return emit('flag', {'extra': False})

reg/templates/reg/accept_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cupcake</title>
    <link href="{{ url_for('main.static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon"/>
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('main.static', filename='resources/Font-Awesome-master/css/font-awesome.min.css') }}"
          rel="stylesheet">
</head>
<body class="body-log">

<div class="wrap-form">

    <h1>{{ context['msg'] }}</h1>
    <br>
    <a href="{{ url_for('main.index_page') }}">Home</a>

</div>
</body>
</html>

reg/templates/reg/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cupcake</title>
    <link href="{{ url_for('main.static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon"/>
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('main.static', filename='resources/Font-Awesome-master/css/font-awesome.min.css') }}"
          rel="stylesheet">
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
</head>
<body class="body-log">

<div class="wrap-form">

    <p class="msg">{{ msg }}</p>
    <form action="{{ url_for('reg.forgot_password') }}" method="post">
        <h1 class="mainLogo "><span>Cup</span>Cake</h1>
        <span class="incorrect">{{ context.msg }}</span>
        <div class="log-fls">

            <input type="email" name="email"
                   placeholder="E-mail" required aria-required="true"><br>

            <input type="submit" value="Confirm"><br>
            <a href="{{ url_for('reg.register') }}" class="register">REGISTER / </a>
            <a href="{{ url_for('reg.login') }}" class="login">LOGIN</a>
        </div>

    </form>

</div>

</body>
</html>

reg/templates/reg/flash_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cupcake</title>
    <link href="{{ url_for('main.static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon"/>
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('main.static', filename='resources/Font-Awesome-master/css/font-awesome.min.css') }}"
          rel="stylesheet">
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
</head>
<body class="body-log">

<div class="wrap-form flash">
    <h1 class="mainLogo "><span>Cup</span>Cake</h1>
    <h1 class="checkMail">{{ context['msg'] }}</h1>
    <a href="{{ url_for('main.index_page') }}">
        <h1 class="checkMail blue">Return to main page</h1>
    </a>

</div>
</body>
</html>

reg/templates/reg/forgot_pass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cupcake</title>
    <link href="{{ url_for('main.static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon"/>
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('main.static', filename='resources/Font-Awesome-master/css/font-awesome.min.css') }}"
          rel="stylesheet">
</head>
<body class="body-log">

<div class="wrap-form">

    <p class="msg">{{ msg }}</p>
    <form action="{{ url_for('reg.new_password', s=session.act_str_for_password) }}" method="post">
        <h1 class="mainLogo"><span>Cup</span>Cake</h1>
        <span class="incorrect">{{ context.msg }}</span>
        <div class="log-fls">

            <input type="password" name="pass1"
                   placeholder="Password" required aria-required="true"><br>
            <input type="password" name="pass2"
                   placeholder="Password" required aria-required="true"><br>


            <input type="submit" value="Confirm"><br>
            <a href="{{ url_for('reg.register') }}" class="register">REGISTER / </a>
            <a href="{{ url_for('reg.login') }}" class="login">LOGIN</a>
        </div>

    </form>

</div>

</body>
</html>

reg/templates/reg/handling_pass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cupcake</title>
    <link href="{{ url_for('main.static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon"/>
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('main.static', filename='resources/Font-Awesome-master/css/font-awesome.min.css') }}"
          rel="stylesheet">
</head>
<body class="body-log">

<div class="wrap-form">

    <p class="msg">{{ msg }}</p>
    <form action="{{ context['action'] }}" method="post">
        <h1 class="mainLogo"><span>Cup</span>Cake</h1>
        <span class="incorrect">{{ context.msg }}</span>
        <div class="log-fls">

            <input type="password" name="pass1"
                   placeholder="Password" required aria-required="true"><br>
            <input type="password" name="pass2"
                   placeholder="Password" required aria-required="true"><br>


            <input type="submit" value="Confirm"><br>
            <a href="{{ url_for('reg.register') }}" class="register">REGISTER / </a>
            <a href="{{ url_for('reg.login') }}" class="login">LOGIN</a>
        </div>

    </form>

</div>

</body>
</html>

reg/templates/reg/login.html
<div class="wrap-form">

    <p class="msg">{{ msg }}</p>
    <div class="cupcake-logo">
        <img src="{{ url_for('main.static', filename='img/cake.png') }}">
    </div>
    <form action="{{ url_for('reg.login') }}" method="post">
        <h1 class="mainLogo "><span>Cup</span>Cake</h1>
        <span class="incorrect">{{context.msg}}</span>
        <div class="log-fls">

            <input id="log-email" type="email" name="email"
                   placeholder="E-mail" required aria-required="true" value="{{ context['email']  }}"><br>
            <input id="log-pass" type="password" name="password" placeholder="Password" aria-required="true"><br>


            <input type="submit" value="Confirm"><br>
            <a href="{{ url_for('reg.register') }}" class="register">REGISTER / </a>
            <a href="{{ url_for('reg.forgot_password') }}" class="forgot">FORGOT PASSWORD</a>
        </div>

    </form>

    <script>
        $('body').addClass('body-log');
    </script>


</div>

reg/templates/reg/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CupCake register</title>
    <link href="{{ url_for('main.static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon"/>
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('main.static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('main.static', filename='resources/Font-Awesome-master/css/font-awesome.min.css') }}" rel="stylesheet">
    <script src="{{ url_for('main.static', filename='js/lib/jquery-2.2.0.js') }}"></script>
    <script src="{{ url_for('main.static', filename='js/lib/socket.io.min.js') }}"></script>
</head>
<body class="body-log">

<div class="wrap-form">

    <p class="msg">{{ msg }}</p>
    <div class="cupcake-logo">
        <img src="{{ url_for('main.static', filename='img/cake.png') }}">
    </div>
    <form action="{{ url_for('reg.register') }}" method="post">
        <h1 class="mainLogo "><span>Cup</span>Cake</h1>
        <span class="incorrect">{{context.msg}}</span>
        <div class="log-fls">

            <div class="check"><input id="log-f-user" type="text" name="first-name" placeholder="First name" required aria-required="true" value="{{ context['first_name']  }}" onchange="checkValue(this, this.value, 0)"><br>
            <i class="fa fa-check"></i><i class="fa fa-times"></i></div>
            <div class="check"><input id="log-l-user" type="text" name="last-name" placeholder="Last name" required aria-required="true" value="{{ context['last_name']  }}" onchange="checkValue(this, this.value, 1)"><br>
            <i class="fa fa-check"></i><i class="fa fa-times"></i></div>
            <div class="check"><input id="log-email" type="email" name="email" placeholder="Email" required aria-required="true" value="{{ context['email']  }}" onchange="checkValue(this, this.value, 2)">
            <i class="fa fa-check"></i><i class="fa fa-times"></i></div>
            <input type="submit" value="Confirm"><br>
            <a href="{{ url_for('reg.login') }}" class="register">LOGIN / </a>
            <a href="{{ url_for('reg.forgot_password') }}" class="forgot">FORGOT PASSWORD</a>
        </div>

    </form>


</div>


<script src="{{ url_for('main.static', filename='js/treatment_page.js') }}"></script>
<script src="{{ url_for('main.static', filename='js/validations.js') }}"></script>

</body>
</html>